# Generated by Django 3.0.3 on 2020-02-12 23:03

from django.db import migrations, models
import django.db.models.deletion
import draw_menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seq', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('seq', models.PositiveSmallIntegerField()),
                ('path', draw_menu.models.TreePathField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='draw_menu.Item')),
                ('part_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw_menu.Menu')),
            ],
        ),
    ]
